### ISSUE TITLE
Consider adding a function to specify the neighbourhood used to define a cluster

### ISSUE THREAD

**Issue by Ashishk6564** [spatial-ews/spatialwarnings#114]
The *_sews function can only be used for Von-Neumann neighbourhood, which considers the edges surrounding a selected cell. Other functions such as 'patchsizes' and 'label' allows customisation of the neighbours to be selected using 'nbmask'. If this is included in *_sews functions, it would allow for analysis of clusters for specific patterns. For example, if I want to use Moore neighbourhood (which includes the cells adjacent to a selected cell edgewise and diagonally), I would have to use 'patchsizes' and then analyse the list of patches separately. If customisation of neighbourhood is added to *_sews function, it can be readily used.

**Comment by alexgenin** [comment]
Hi Ashish, this would definitely be a good improvement to the package, and probably not too hard to implement. I will have a look at it when I find some time :)

**Comment by alexgenin** [comment]
Hi Ashish, in spatiawarnings master, you can now use this to specify the type of neighborhood: 
```r
patchdistr_sews(forestgap[1:3], nbmask = "moore") 
```
(or `"von_neumann"`, depending on the type of neighborhood you want). As usual, install with `devtools::install_github("spatial-ews/spatialwarnings")`. 

Cheers, 

Alex

**Comment by Ashishk6564** [comment]
Hi Dr. Genin,
Thank you for adding this.

Warm regards,

Ashish

**Comment by alexgenin** [comment]
This is now implemented and ready for next release.
