### ISSUE TITLE
Make the package CRAN-compatible

### ISSUE THREAD

**Issue by alexgenin** [spatial-ews/spatialwarnings#20]
If we plan to submit our package on the CRAN, we need to pass all the required automatic tests. CRAN reviewers are very strict about this so all NOTEs/WARNINGs/ERRORs _must_ be squashed.

The package can be checked within R using the `devtools::check()` function. Pass the argument `cran=TRUE` to run a CRAN-like check. 

Note that this is not to be confused with the unit-tests run using `test()`. What `check()` does is checking whether the package will be runnable on other computers and whether it follows the CRAN guidelines. (check() run the unit tests though and stops if those fail).

Example output: 

``` r
* using log directory ‘<snip>/spatial_warnings.Rcheck’
* using R version 3.2.1 (2015-06-18)
<snip>
Status: 1 ERROR, 10 WARNINGs, 6 NOTEs
See
```

**Comment by alexgenin** [comment]
I just asked for a repo on r-forge so we can use their package-building service (answer within 72h).

**Comment by alexgenin** [comment]
OK I created the project on R-forge: https://r-forge.r-project.org/projects/spwarnings/

This will allow us to have binary packages checked and built for linux and windows, and then submit to CRAN. I set up a script that sends the most recent versions of caspr and spatialwarnings for building on R-forge twice per day. Then R-forge scans the packages for errors and tries to build binary packages that can be installed with `install.packages()`.

You can check out the results of package building on [this page](http://r-forge.r-project.org/R/?group_id=2137). It can have different statuses (Failed to build, Building... or Current). Right now package-building fails as there are errors in the package. You can check the details of these errors under the package extra info (package check for the two platforms Linux x86_64 and windows).

For example, right now the [log](http://r-forge.r-project.org/R/?group_id=2137&log=check_x86_64_linux&pkg=spatialwarnings&flavor=patched) reports several errors in examples, in the DESCRIPTION file, etc. All warnings and errors need to be fixed before submission to CRAN (and most of NOTEs). Most of them are really simple things like non-english (ASCII) characters in help, lacks of documentation, missing fields in DESCRIPTION, etc...

If you want write access to the repository and you have an R-forge account I can give you full access to it of course.

**Comment by alexgenin** [comment]
Here is a list of not-very-technical erros taken from the build [log](http://r-forge.r-project.org/R/?group_id=2137&log=check_x86_64_linux&pkg=spatialwarnings&flavor=patched) with the relevant sections of the log: 

 - [ ] List correct authors/etc. in DESCRIPTION file
```r
* checking CRAN incoming feasibility ... NOTE
Maintainer: ‘Add Me ’
New submission

Non-FOSS package license (addme)
Found the following (possibly) invalid URLs:
  URL: https://github.com/fdschneider/spatial_warnings/blob/master/R/FGcore.R
    From: README.md
    Status: 404
    Message: Not Found
  URL: https://github.com/fdschneider/spatial_warnings/blob/master/R/Indicator_FractalGeometry.R
    From: README.md
    Status: 404
    Message: Not Found
  URL: https://github.com/fdschneider/spatial_warnings/blob/master/R/fitpsd.R
    From: README.md
    Status: 404
    Message: Not Found
  URL: https://github.com/fdschneider/spatial_warnings/blob/master/R/generic_spatial_indicators.R
    From: README.md
    Status: 404
    Message: Not Found
  URL: https://github.com/fdschneider/spatial_warnings/blob/master/R/indicator_variance_main.R
    From: README.md
    Status: 404
    Message: Not Found
  URL: https://github.com/fdschneider/spatial_warnings/blob/master/R/lbl.R
    From: README.md
    Status: 404
    Message: Not Found
  URL: https://github.com/fdschneider/spatial_warnings/blob/master/R/morancorrelation_ews.R
    From: README.md
    Status: 404
    Message: Not Found
  URL: https://github.com/fdschneider/spatial_warnings/blob/master/R/patchsizedistr_ews.R
    From: README.md
    Status: 404
    Message: Not Found

The Description field should not start with the package name,
  'This package' or similar.

The Date field is over a month old.
```

- [ ] Check if this file is really needed: if not delete it from the repo, if yes then add a line in the .Rbuildignore file with the filename 
```r
* checking if this is a source package ... WARNING
Subdirectory ‘src’ contains:
  headers.hpp
These are unlikely file names for src files.
```

 - [ ] Add this folder to .Rbuildignore
```r
* checking top-level files ... NOTE
Non-standard file/directory found at top level:
  ‘draft’
```

 - [ ] Check if we actually use functions from these packages and delete them from dependecies if we do not
```r
* checking dependencies in R code ... NOTE
Namespaces in Imports field not imported from:
  ‘SDMTools’ ‘fields’ ‘plotrix’
  All declared Imports should be used.
```

 - [ ] Check if the functions there actually exist in the package :
```r
* checking R code for possible problems ... NOTE
as.binary_matrix.list: no visible binding for global variable
  ‘as.binary.matrix’
indicator_example_with_interm_result: no visible global function
  definition for ‘compute_it’
indicator_fitpsd: no visible binding for global variable ‘p_spanning’
```

 - [ ] Doc missing  
```r
Undocumented data sets:
  ‘B’ ‘B200f’ ‘B200p’ ‘B50m’ ‘B50p’ ‘L’ ‘L200f’ ‘L200p’ ‘L50m’ ‘L50p’
All user-level objects in a package should have documentation entries.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
```

**Comment by guttal** [comment]
Hi Alex, Could you please suggest some sample Read.md documentation to see how these Read.md files should be written?

**Comment by guttal** [comment]
Okay, I found this link  (http://r-pkgs.had.co.nz/release.html) that explains various aspects including writing Read.md file. I will try to work on it whenever I get time.

**Comment by alexgenin** [comment]
Hello there, 

I definitely recommend the R packages book you linked! The README.md file is basically what appears on the github homepage so another idea is using the one we [use for caspr](https://raw.githubusercontent.com/fdschneider/caspr/master/README.md) as example.

**Comment by alexgenin** [comment]
Package builds at r-forge now: http://r-forge.r-project.org/R/?group_id=2137

**Comment by alexgenin** [comment]
Closing this because it's only a matter of adding the doc now.
