### ISSUE TITLE
[spatial variance] some comments

### ISSUE THREAD

**Issue by guttal** [spatial-ews/spatialwarnings#66]
We made some edits to documentation of spatial variance. Some comments:

1) We prefer to remove the option detrending, since detrending a spatial data requires fitting a surface, not just subtracting mean uniformly for the entire matrix. 

2) Why 'subsize' is logical? Isn't that an integer? Check the redefinition.

**Comment by alexgenin** [comment]
1. Removing the detrending option sounds good, will do ! 

2. I'm confused, where is subsize used as a logical ? Maybe this message [line](https://github.com/spatial-ews/spatialwarnings/blob/01cfef9aebb899742e463a10ee217941e73130a4/R/task_generic_indic.R#L135) is confusing ? I'll try to find a better formulation if so. 

Thanks !
