### ISSUE TITLE
Documentation of patchdistr_spews

### ISSUE THREAD

**Issue by skefi** [spatial-ews/spatialwarnings#70]
In the documentation of patchdistr_spews: 
https://github.com/spatial-ews/spatialwarnings/blob/master/R/task_patch_indic.R
- the explanation of xmin (in arguments) is not very clear: xmin is calculated for the PL fit using Clauset and then the same xmin is applied to all the other fits? 
- I would also add in the 'examples' section:
plot(psd_indic)
psd_indic.res <- as.data.frame(psd_indic) #exports the results

**Comment by skefi** [comment]
To ease the understanding of the result file, it might also be good to add in the text: 
"The best discrete distribution is estimated among these candidates: a power-law x^λ ('expo' in the the result output), an exponential exp(α x) ('rate' in the result output)..."?

**Comment by alexgenin** [comment]
OK, this is done now.
