### ISSUE TITLE
Buttita et al's Extreme Value Distribution

### ISSUE THREAD

**Issue by alexgenin** [spatial-ews/spatialwarnings#75]
Buttita et al [1] mention the Extreme Value Distribution as a possible spatial indicator. Maybe something worth implementing ?

[1] http://onlinelibrary.wiley.com/doi/10.1002/ecs2.1941/full

**Comment by alexgenin** [comment]
Closing this because of a lack of interest.

**Comment by guttal** [comment]
It may be difficult to statistically get a good estimate for rare events. So good to close this!
