### ISSUE TITLE
Connectivity measures

### ISSUE THREAD

**Issue by alexgenin** [spatial-ews/spatialwarnings#80]
For drylands, connectivity of the landscape could reflect degradation, provided it comes with a relevant null model, see: 

https://www.sciencedirect.com/science/article/pii/S1470160X1730660X

Maybe something to make available in spatialwarnings ?

**Comment by alexgenin** [comment]
Angie, could you please attach the following files to this issue ? Thanks very much !!!

 - [ ] Code to compute the constant slope connectivity
 - [ ] Raw data for Figure 4 of Rodriguez et al. (2017) (x/y values of the graph)
 - [ ] Matrices (output from the model) that were used to compute the FL in Fig. 4
 - [ ] Raw image files from the appendix (Figure S1)

And maybe ? 
 - [ ] Code to compute the real-topography connectivity indicator

Other useful refs on this topic are: Mayor et al. (2008)

**Comment by agmayor** [comment]
Alex, I'm attaching here the next items:
1. Raw image files in Figure S1 (Appendix B) of Rodríguez et al. (2018, http://dx.doi.org/10.1016/j.ecolind.2017.10.023):
[images_FigS1_Rodriguez_et_al_2018.zip](https://github.com/spatial-ews/spatialwarnings/files/2382487/images_FigS1_Rodriguez_et_al_2018.zip)
2. Raw data for Fig4 of Rodríguez et al. (2018, http://dx.doi.org/10.1016/j.ecolind.2017.10.023):
[data_Fig4_Rodriguez_et_al_2018.txt](https://github.com/spatial-ews/spatialwarnings/files/2382501/data_Fig4_Rodriguez_et_al_2018.txt)

More coming soon!

**Comment by alexgenin** [comment]
OK, so the planar version of FL is implemented in git master. The code matches what is expected for column vectors filled with a given proportion of vegetation, but we need more testing to make sure the computation is correct for 2D matrices.

**Comment by alexgenin** [comment]
As promised, some news !

 - the uniform slope flowlength is now available on CRAN along with spatialwarnings 1.3.1. It works correctly, as tested from the images. The 'arizona' images are included with the package as a dataset to play with.
 - the code for the "real" flowlength does not look too complex (~500 lines). In fact, most of the file is dedicated to reading/writing data,etc. which becomes handled by R once in a package and does not need reimplementation. The tricky part would be adapting it to fit the R package format (i.e. convert to Rcpp data structures) and making sure the results are correct. There is also a need to know from where the code comes from, to make sure the original author agrees with his/her code being included in a MIT-licensed package before anything. All in all it does represent some work time (which I'm not sure I'll have enough of), maybe a few days worth of work, but it's not too bad (hing: it could be a good contribution from an R-enthusiast to the package !)

**Comment by alexgenin** [comment]
I am closing this for now. We can reopen it when there is interest for the non-planar flowlength.
